ALTER TABLE users ADD COLUMN IF NOT EXISTS status ENUM('active','inactive') NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE users ADD UNIQUE KEY IF NOT EXISTS users_email_unique (email);

ALTER TABLE services ADD COLUMN IF NOT EXISTS provider_id BIGINT UNSIGNED NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS provider_service_id VARCHAR(120) NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_name VARCHAR(190) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_category VARCHAR(120) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_price BIGINT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS provider_order_id VARCHAR(120) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_note VARCHAR(500) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refunded_at DATETIME NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE deposits ADD COLUMN IF NOT EXISTS admin_note VARCHAR(500) NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS processed_by BIGINT UNSIGNED NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS tanggal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS processed_at DATETIME NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE balance_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    admin_user_id BIGINT UNSIGNED NULL,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT UNSIGNED NULL,
    old_value JSON NULL,
    new_value JSON NULL,
    ip_address VARCHAR(80) NULL,
    user_agent VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY audit_admin_idx (admin_user_id, id),
    KEY audit_target_idx (target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(80) NOT NULL,
    title VARCHAR(190) NOT NULL,
    message VARCHAR(500) NOT NULL,
    target_role ENUM('admin','user') NOT NULL DEFAULT 'admin',
    reference_type VARCHAR(80) NULL,
    reference_id BIGINT UNSIGNED NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    read_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY notifications_target_idx (target_role, is_read, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(128) NOT NULL PRIMARY KEY,
    expires INT(11) UNSIGNED NOT NULL,
    data MEDIUMTEXT,
    KEY sessions_expires_idx (expires)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
